Dalys
mrc-ide/postie pull request #4
Opened 2023-07-27 10:18 UTC by lmhaile

Resolves comments in [this PR](https://github.com/mrc-ide/postie/pull/2).

Additionally incorporates updated treatment scaler per Nora's research.

2023-07-27 14:46 UTC, pwinskill requested changes

2023-07-27 14:46 UTC, pwinskill commented on R/epi.R
> +    clinical_episode_length = 0.01375 * 365,
These should not be multiplied by 365. The output of the DALYs is in years and the units of these parameters are in years already. 
E.g. The length of a clinical episode is ~ 5 days = 0.01375 years, so the number of diability adjusted life _years_ is cases * weight * 0.1375 years.

2023-07-27 14:46 UTC, pwinskill commented on R/rates.R
> +                      clinical_episode_length = 0.01375 * 365,
See other comment

2023-07-27 14:46 UTC, pwinskill commented on tests/testthat/test-epi.R
> +  expect_equal(output_ts$severe, mock_data$severe * ((0.57 * mock_data$ft + (1 - mock_data$ft)) / (0.57 * 0.4 + (1 - 0.4))))
Can we change `0.57` to `(1 - 0.43)` in these examples, just so it is obvious where it came from?

2023-07-27 14:46 UTC, pwinskill commented on tests/testthat/test-rates.R
> +    yld_pp = 0.0001338985*365,
As before

2023-07-27 15:51 UTC, lmhaile commented
Comments incorporated now!

2023-07-28 09:13 UTC, pwinskill commented
Are there still some * 365 in get_rates?

2023-08-02 22:40 UTC, lmhaile commented
> Are there still some * 365 in get_rates?

You're correct, should be fixed with the latest commit!

2023-08-04 09:45 UTC, merged